// <auto-generated />
using System;
using System.Text.Json;
using MemoWords.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MemoWords.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "event_type", new[] { "generate_clicked", "translate_generated", "translate_failed", "card_added_after_generate", "edit_saved", "delete_confirmed", "dialog_add_canceled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MemoWords.Api.Domain.Entities.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<string>("TargetText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("UserId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("idx_cards_user_created_id");

                    b.ToTable("cards", "public", t =>
                        {
                            t.HasCheckConstraint("ck_cards_source_text_len", "char_length(btrim(source_text)) BETWEEN 1 AND 500");

                            t.HasCheckConstraint("ck_cards_source_text_not_blank", "btrim(source_text) <> ''");

                            t.HasCheckConstraint("ck_cards_target_text_len", "char_length(btrim(target_text)) BETWEEN 1 AND 500");

                            t.HasCheckConstraint("ck_cards_target_text_not_blank", "btrim(target_text) <> ''");
                        });
                });

            modelBuilder.Entity("MemoWords.Api.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiModel")
                        .HasColumnType("text")
                        .HasColumnName("ai_model");

                    b.Property<Guid?>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("error_code");

                    b.Property<JsonDocument>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<int>("Type")
                        .HasColumnType("public.event_type")
                        .HasColumnName("type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("CardId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_events_card_created");

                    b.HasIndex("Type", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_events_type_created");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_events_user_created");

                    b.ToTable("events", "public");
                });

            modelBuilder.Entity("MemoWords.Api.Domain.Entities.Event", b =>
                {
                    b.HasOne("MemoWords.Api.Domain.Entities.Card", "Card")
                        .WithMany("Events")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_events_cards_card_id");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("MemoWords.Api.Domain.Entities.Card", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
